apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-server-daemons
  name: home-server-daemons
  namespace: home-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-server-daemons
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-server-daemons
    spec:
      containers:
        - name: i2p
          image: ghcr.io/duddu/home-server-i2p
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
              hostPort: 4444
              protocol: TCP
            - containerPort: 7657
              hostPort: 7657
              protocol: TCP
          volumeMounts:
            - mountPath: /i2p/.i2p
              name: nfs-i2p-pvc
          livenessProbe:
            exec:
              command:
                - i2p-healthcheck.sh
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 120
            failureThreshold: 3
#         - name: monero
#           image: ghcr.io/duddu/home-server-monero
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 18082
#               hostPort: 18082
#               protocol: TCP
#           env:
#             - name: MONERO_RPC_LOGIN
#               valueFrom:
#                 secretKeyRef:
#                   name: monero
#                   key: rpc_login
#                   optional: false
#             - name: MONERO_PEERS
#               valueFrom:
#                 secretKeyRef:
#                   name: monero
#                   key: tor_peers
#                   optional: false
#           resources:
#             requests:
#               cpu: "1000m"
#               memory: "2048Mi"
#           volumeMounts:
#             - mountPath: /root/monero
#               name: nfs-monero-pvc
#           livenessProbe:
#             exec:
#               command:
#                 - monero-healthcheck.sh
#             initialDelaySeconds: 600
#             timeoutSeconds: 120
#             periodSeconds: 600
#             failureThreshold: 3
      dnsPolicy: ClusterFirst
      hostname: home-server-daemons
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nfs-i2p-pvc
          persistentVolumeClaim:
            claimName: nfs-i2p
#         - name: nfs-monero-pvc
#           persistentVolumeClaim:
#             claimName: nfs-monero
