apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-server-daemons
  name: home-server-daemons
  namespace: home-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-server-daemons
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-server-daemons
    spec:
      containers:
        - image: ghcr.io/duddu/home-server-google-ddns:0.2.0
          imagePullPolicy: Always
          name: google-ddns
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: GOOGLE_DDNS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: google-ddns-credentials
                  key: username
                  optional: false
            - name: GOOGLE_DDNS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: google-ddns-credentials
                  key: password
                  optional: false
          livenessProbe:
            exec:
              command:
                - google-ddns-healthcheck.sh
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 1200
            failureThreshold: 3
        - image: ghcr.io/duddu/home-server-monero:0.4.0
          imagePullPolicy: Always
          name: monero
          ports:
            - containerPort: 18082
              hostPort: 18082
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/monero
              name: nfs-monero-pvc
          livenessProbe:
            exec:
              command:
                - monero-healthcheck.sh
            initialDelaySeconds: 600
            timeoutSeconds: 60
            periodSeconds: 300
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      hostname: home-server-daemons
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nfs-monero-pvc
          persistentVolumeClaim:
            claimName: nfs-monero