apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-acme
  namespace: home-server
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/.acme.sh"
  mountOptions:
    - async
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-gnupg
  namespace: home-server
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/.gnupg"
  mountOptions:
    - async
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-i2p
  namespace: home-server
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/.i2p"
  mountOptions:
    - async
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monero
  namespace: home-server
spec:
  capacity:
    storage: 96Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/monero"
  mountOptions:
    - async
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-public-ip
  namespace: home-server
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/public-ip"
  mountOptions:
    - async
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-scaffolding
  namespace: home-server
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/scaffolding"
  mountOptions:
    - async
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-ssl
  namespace: home-server
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  nfs:
    server: host.containers.internal
    path: "/System/Volumes/Data/Users/Shared/.podman_volumes/ssl"
  mountOptions:
    - async