apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-acme
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10M
  volumeName: nfs-acme
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-gnupg
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10M
  volumeName: nfs-gnupg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-i2p
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100M
  volumeName: nfs-i2p
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-monero
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 96Gi
  volumeName: nfs-monero
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-public-ip
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1M
  volumeName: nfs-public-ip
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-scaffolding
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10M
  volumeName: nfs-scaffolding
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ssl
  namespace: home-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10M
  volumeName: nfs-ssl