apiVersion: v1
kind: PersistentVolumeClaim
metadata: &metadata
  annotations: &annotations
    volume.podman.io/device: host.containers.internal:/System/Volumes/Data/Users/Shared/.podman_volumes/.acme.sh
    volume.podman.io/driver: local
    volume.podman.io/mount-options: async
    volume.podman.io/type: nfs
    volume.podman.io/uid: 4294967294
  creationTimestamp: "2022-10-30T02:09:17Z"
  name: nfs_acme
spec: &spec
  accessModes:
  - ReadWriteOnce
  resources: &resources
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  <<: *metadata
  annotations:
    <<: *annotations
    volume.podman.io/device: host.containers.internal:/System/Volumes/Data/Users/Shared/.podman_volumes/.gnupg
  name: nfs_gnupg
spec: *spec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  <<: *metadata
  annotations:
    <<: *annotations
    volume.podman.io/device: host.containers.internal:/System/Volumes/Data/Users/Shared/.podman_volumes/monero
  name: nfs_monero
spec:
  <<: *spec
  resources:
    <<: *resources
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  <<: *metadata
  annotations:
    <<: *annotations
    volume.podman.io/device: host.containers.internal:/System/Volumes/Data/Users/Shared/.podman_volumes/ssl
  name: nfs_ssl
spec: *spec