apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/home-server-nginx-reverse-proxy: container
    io.kubernetes.cri-o.ContainerType/home-server-rust-api: container
    io.kubernetes.cri-o.SandboxID/home-server-nginx-reverse-proxy: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.SandboxID/home-server-rust-api: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.TTY/home-server-nginx-reverse-proxy: "true"
    io.kubernetes.cri-o.TTY/home-server-rust-api: "true"
    io.podman.annotations.autoremove/home-server-nginx-reverse-proxy: "TRUE"
    io.podman.annotations.autoremove/home-server-rust-api: "TRUE"
    io.podman.annotations.init/home-server-nginx-reverse-proxy: "FALSE"
    io.podman.annotations.init/home-server-rust-api: "FALSE"
    io.podman.annotations.privileged/home-server-nginx-reverse-proxy: "FALSE"
    io.podman.annotations.privileged/home-server-rust-api: "FALSE"
    io.podman.annotations.publish-all/home-server-nginx-reverse-proxy: "FALSE"
    io.podman.annotations.publish-all/home-server-rust-api: "FALSE"
  creationTimestamp: "2022-09-06T02:43:42Z"
  labels:
    app: home-server
  name: home-server
spec:
  containers:
  - image: ghcr.io/duddu/home-server-rust-api:latest
    name: home-server-rust-api
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    image: ghcr.io/duddu/home-server-nginx-reverse-proxy:latest
    name: home-server-nginx-reverse-proxy
    imagePullPolicy: Always
    ports:
    - containerPort: 443
      hostPort: 4433
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /etc/ssl/certs/davidedoronzo_myddns_me.pem-chain
      name: ssl-certs-davidedoronzo_myddns_me.pem-chain
      readOnly: true
    - mountPath: /etc/ssl/private/davidedoronzo_myddns_me.key
      name: ssl-private-davidedoronzo_myddns_me.key
      readOnly: true
    - mountPath: /etc/ssl/certs/davidedoronzo-ca.pem
      name: ssl-certs-davidedoronzo-ca.pem
      readOnly: true
  hostname: home-server
  restartPolicy: Always
  volumes:
  - hostPath:
      path: $PWD/packages/nginx-reverse-proxy/ssl/certs/davidedoronzo_myddns_me.pem-chain
      type: File
    name: ssl-certs-davidedoronzo_myddns_me.pem-chain
  - hostPath:
      path: $PWD/packages/nginx-reverse-proxy/ssl/private/davidedoronzo_myddns_me.key
      type: File
    name: ssl-private-davidedoronzo_myddns_me.key
  - hostPath:
      path: $PWD/packages/nginx-reverse-proxy/ssl/certs/davidedoronzo-ca.pem
      type: File
    name: ssl-certs-davidedoronzo-ca.pem