apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/scaffolding: container
    io.kubernetes.cri-o.ContainerType/nginx-reverse-proxy: container
    io.kubernetes.cri-o.ContainerType/rust-api: container
    io.kubernetes.cri-o.ContainerType/monero: container
    io.kubernetes.cri-o.SandboxID/scaffolding: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.SandboxID/nginx-reverse-proxy: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.SandboxID/rust-api: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.SandboxID/monero: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.TTY/scaffolding: "true"
    io.kubernetes.cri-o.TTY/nginx-reverse-proxy: "true"
    io.kubernetes.cri-o.TTY/rust-api: "true"
    io.kubernetes.cri-o.TTY/monero: "true"
    io.podman.annotations.autoremove/scaffolding: "TRUE"
    io.podman.annotations.autoremove/nginx-reverse-proxy: "TRUE"
    io.podman.annotations.autoremove/rust-api: "TRUE"
    io.podman.annotations.autoremove/monero: "TRUE"
    io.podman.annotations.init/scaffolding: "FALSE"
    io.podman.annotations.init/nginx-reverse-proxy: "FALSE"
    io.podman.annotations.init/rust-api: "FALSE"
    io.podman.annotations.init/monero: "FALSE"
    io.podman.annotations.privileged/scaffolding: "FALSE"
    io.podman.annotations.privileged/nginx-reverse-proxy: "FALSE"
    io.podman.annotations.privileged/rust-api: "FALSE"
    io.podman.annotations.privileged/monero: "FALSE"
    io.podman.annotations.publish-all/scaffolding: "FALSE"
    io.podman.annotations.publish-all/nginx-reverse-proxy: "FALSE"
    io.podman.annotations.publish-all/rust-api: "FALSE"
    io.podman.annotations.publish-all/monero: "FALSE"
  creationTimestamp: "2022-09-06T02:43:42Z"
  labels:
    app: home-server
  name: home-server
spec:
  containers:
  - image: ghcr.io/duddu/home-server-scaffolding:0.3.1
    name: scaffolding
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext: &securityContext
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /root/.acme.sh
      name: nfs_acme-pvc
    - mountPath: /root/.gnupg
      name: nfs_gnupg-pvc
    - mountPath: /usr/local/home-server/packages/nginx-reverse-proxy/ssl
      name: nfs_ssl-pvc
    livenessProbe:
      exec:
        command:
        - healthcheck.sh
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 60
      failureThreshold: 3
  - image: ghcr.io/duddu/home-server-nginx-reverse-proxy:0.17.1
    name: nginx-reverse-proxy
    imagePullPolicy: Always
    ports:
    - containerPort: 8443
      hostPort: 8443
    - containerPort: 8081
      hostPort: 8081
    - containerPort: 9091
      hostPort: 9091
    securityContext: *securityContext
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /usr/local/share/ssl
      name: nfs_ssl-pvc
    livenessProbe:
      exec:
        command:
        - healthcheck.sh
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 60
      failureThreshold: 3
  - image: ghcr.io/duddu/home-server-rust-api:0.13.0
    name: rust-api
    imagePullPolicy: Always
    ports:
    - containerPort: 9092
      hostPort: 9092
    securityContext: *securityContext
    stdin: true
    tty: true
    livenessProbe:
      exec:
        command:
        - home-server-rust-api-healthcheck
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 60
      failureThreshold: 3
  - image: ghcr.io/duddu/home-server-monero:0.2.1
    name: monero
    imagePullPolicy: Always
    ports:
    - containerPort: 9093
      hostPort: 9093
    securityContext: *securityContext
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /root/monero
      name: nfs_monero-pvc
    livenessProbe:
      exec:
        command:
        - healthcheck.sh
      initialDelaySeconds: 5
      timeoutSeconds: 10
      periodSeconds: 60
      failureThreshold: 3
  hostname: home-server
  restartPolicy: Always
  volumes:
  - name: nfs_acme-pvc
    persistentVolumeClaim:
      claimName: nfs_acme
  - name: nfs_gnupg-pvc
    persistentVolumeClaim:
      claimName: nfs_gnupg
  - name: nfs_monero-pvc
    persistentVolumeClaim:
      claimName: nfs_monero
  - name: nfs_ssl-pvc
    persistentVolumeClaim:
      claimName: nfs_ssl