apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/nginx-reverse-proxy: container
    io.kubernetes.cri-o.ContainerType/rust-api: container
    io.kubernetes.cri-o.SandboxID/nginx-reverse-proxy: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.SandboxID/rust-api: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.TTY/nginx-reverse-proxy: "true"
    io.kubernetes.cri-o.TTY/rust-api: "true"
    io.podman.annotations.autoremove/nginx-reverse-proxy: "TRUE"
    io.podman.annotations.autoremove/rust-api: "TRUE"
    io.podman.annotations.init/nginx-reverse-proxy: "FALSE"
    io.podman.annotations.init/rust-api: "FALSE"
    io.podman.annotations.privileged/nginx-reverse-proxy: "FALSE"
    io.podman.annotations.privileged/rust-api: "FALSE"
    io.podman.annotations.publish-all/nginx-reverse-proxy: "FALSE"
    io.podman.annotations.publish-all/rust-api: "FALSE"
  creationTimestamp: "2022-09-06T02:43:42Z"
  labels:
    app: home-server
  name: home-server
spec:
  containers:
  - image: ghcr.io/duddu/home-server-rust-api:0.11.2
    name: rust-api
    imagePullPolicy: Always
    ports:
    - containerPort: 8889
      hostPort: 8889
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  - image: ghcr.io/duddu/home-server-nginx-reverse-proxy:0.11.3
    name: nginx-reverse-proxy
    imagePullPolicy: Always
    ports:
    - containerPort: 8443
      hostPort: 8443
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 8888
      hostPort: 8888
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /usr/share/nginx/ssl
      name: nginx-reverse-proxy_ssl
      readOnly: true
  hostname: home-server
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /var/home/core/.home-server/packages/nginx-reverse-proxy/ssl
      type: Directory
    name: nginx-reverse-proxy_ssl