apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/nginx-home-server-proxy: container
    io.kubernetes.cri-o.ContainerType/rust-home-server-api: container
    io.kubernetes.cri-o.SandboxID/nginx-home-server-proxy: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.SandboxID/rust-home-server-api: baa86e67b0c9f5f902e8801d48d73f04b3742cf18ba378185ed06866070cfe3
    io.kubernetes.cri-o.TTY/nginx-home-server-proxy: "true"
    io.kubernetes.cri-o.TTY/rust-home-server-api: "true"
    io.podman.annotations.autoremove/nginx-home-server-proxy: "TRUE"
    io.podman.annotations.autoremove/rust-home-server-api: "TRUE"
    io.podman.annotations.init/nginx-home-server-proxy: "FALSE"
    io.podman.annotations.init/rust-home-server-api: "FALSE"
    io.podman.annotations.privileged/nginx-home-server-proxy: "FALSE"
    io.podman.annotations.privileged/rust-home-server-api: "FALSE"
    io.podman.annotations.publish-all/nginx-home-server-proxy: "FALSE"
    io.podman.annotations.publish-all/rust-home-server-api: "FALSE"
  creationTimestamp: "2022-09-06T02:43:42Z"
  labels:
    app: home-server
  name: home-server
spec:
  containers:
  - image: docker.io/duddu/rust-home-server-api:latest
    name: rust-home-server-api
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/duddu/nginx-home-server-proxy:latest
    name: nginx-home-server-proxy
    imagePullPolicy: Always
    ports:
    - containerPort: 443
      hostPort: 4433
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /etc/ssl/certs/davidedoronzo_myddns_me.pem-chain
      name: ssl-certs-davidedoronzo_myddns_me.pem-chain
      readOnly: true
    - mountPath: /etc/ssl/private/davidedoronzo_myddns_me.key
      name: ssl-private-davidedoronzo_myddns_me.key
      readOnly: true
    - mountPath: /etc/apache2/.htpasswd
      name: apache2-.htpasswd
      readOnly: true
  hostname: home-server
  restartPolicy: Always
  volumes:
  - hostPath:
      path: $PWD/packages/nginx-reverse-proxy/ssl/certs/davidedoronzo_myddns_me.pem-chain
      type: File
    name: ssl-certs-davidedoronzo_myddns_me.pem-chain
  - hostPath:
      path: $PWD/packages/nginx-reverse-proxy/ssl/private/davidedoronzo_myddns_me.key
      type: File
    name: ssl-private-davidedoronzo_myddns_me.key
  - hostPath:
      path: $PWD/packages/nginx-reverse-proxy/apache2/.htpasswd
      type: File
    name: apache2-.htpasswd