apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-server-daemons
  name: home-server-daemons
  namespace: home-server
spec:
  ports:
    - name: i2p-http-proxy
      port: 4444
      protocol: TCP
      targetPort: 4444
    - name: i2p-console
      port: 7657
      protocol: TCP
      targetPort: 7657
    - name: xmr-rpc-restricted
      port: 18082
      protocol: TCP
      targetPort: 18082
    - name: i2p-xmr-proxy
      port: 48060
      protocol: TCP
      targetPort: 48060
    - name: i2p-xmr-inbound
      port: 48061
      protocol: TCP
      targetPort: 48061
  selector:
    app: home-server-daemons
  sessionAffinity: None