apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-server
  name: home-server
  namespace: home-server
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: home-server
  sessionAffinity: None
