apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job: home-server-google-ddns
  name: home-server-google-ddns
  namespace: home-server
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: home-server-google-ddns
        spec:
          containers:
            - image: ghcr.io/duddu/home-server-google-ddns
              imagePullPolicy: Always
              name: google-ddns
              env:
                - name: GOOGLE_DDNS_LOGIN
                  valueFrom:
                    secretKeyRef:
                      name: google-ddns
                      key: login
                      optional: false
              volumeMounts:
                - mountPath: /var/public-ip
                  name: nfs-public-ip-pvc
          restartPolicy: OnFailure
          volumes:
            - name: nfs-public-ip-pvc
              persistentVolumeClaim:
                claimName: nfs-public-ip