apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job: home-server-scaffolding
  name: home-server-scaffolding
  namespace: home-server
spec:
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      labels:
        job: home-server-scaffolding
    spec:
      containers:
        - image: ghcr.io/duddu/home-server-scaffolding:latest
          imagePullPolicy: Always
          name: scaffolding
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/mason/.gnupg
              name: nfs-gnupg-pvc
            - mountPath: /usr/local/share/home-server
              name: nfs-scaffolding-pvc
            - mountPath: /usr/local/share/ssl
              name: nfs-ssl-pvc
      restartPolicy: Never
      volumes:
        - name: nfs-gnupg-pvc
          persistentVolumeClaim:
            claimName: nfs-gnupg
        - name: nfs-scaffolding-pvc
          persistentVolumeClaim:
            claimName: nfs-scaffolding
        - name: nfs-ssl-pvc
          persistentVolumeClaim:
            claimName: nfs-ssl