[package]
name = "rust-home-server-api"
version = "0.1.2"
edition = "2021"

[dependencies]
futures = "0.3"
serde = "1.0.144"
sysinfo = "0.26.1"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]