[package]
name = "home-server-rust-api"
version = "0.11.2"
edition = "2021"

[dependencies]
futures = "0.3"
serde = "1.0.144"
systemstat = "0.2.1"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]