[package]
name = "home-server-rust-api"
version = "0.14.2"
edition = "2021"

[dependencies]
futures = "0.3"
serde = "1.0.144"
systemstat = "0.2.1"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.reqwest]
version = "0.11.10"
features = ["blocking"]

[[bin]]
name = "home-server-rust-api-healthcheck"
path = "src/bin/healthcheck.rs"