[package]
name = "home-server-rust-api"
version = "0.4.0"
edition = "2021"

[dependencies]
futures = "0.3"
serde = "1.0.144"
sysinfo = "0.26.4"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]