[default]
address = "0.0.0.0"
port = 8000
ident = "home-server-rust-api/0.12.0"

[debug]
log_level = "debug"
cli_colors = true
machine_localhost = "localhost"
domain_name = "localhost"

[release]
log_level = "normal"
cli_colors = false
machine_localhost = "host.containers.internal"