kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: home-server
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8080
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 8443
        hostPort: 8443
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 18082
        hostPort: 18082
        listenAddress: "0.0.0.0"
        protocol: tcp