kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: home-server
# featureGates:
#   NodeSwap: true
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8080
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 8443
        hostPort: 8443
        listenAddress: "0.0.0.0"
        protocol: tcp
    # kubeadmConfigPatches:
    #   - |
    #     kind: KubeletConfiguration
    #     memorySwap:
    #       swapBehavior: UnlimitedSwap