name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  start_home-server_pod:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: SSH into home server
        run: ssh ${{ secrets.SERVER_HOST }} && cd ~ && ls -la

      - uses: actions/checkout@v3

      - name: Unlock encrypted files
        run: cd git-crypt unlock

      - name: Start home-server pod
        run: ./home-server-pod-start.sh
