name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  start_home-server_pod:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy over SSH
        run: ssh ${{ secrets.SERVER_HOST }} "zsh -c 'export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" && git clone git@github.com:${{ github.repository }}.git /tmp/${{ github.run_id }} && cd /tmp/${{ github.run_id }} && git-crypt unlock && HOME=/Users/duddu ./home-server-pod-start.sh' && rm -rf /tmp/${{ github.run_id }}"
