name: Deploy Home Server
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      restart-vm:
        description: 'Restart podman virtual machine before restarting the pod'
        required: true
        default: false 
        type: boolean
  push:
    branches:
      - main
    paths:
      - '.git-crypt/**'
      - '.gitattributes'
      - '.github/workflows/deploy-home-server.yml'
      - 'config/**'
      - 'scripts/**'
concurrency:
  group: deploy-home-server
  cancel-in-progress: true
jobs:
  apply-k8s-resources:
    name: Apply k8s resources
    uses: ./.github/workflows/run-over-ssh.yml
    secrets: inherit
    with:
      script-name: home-server-deploy
      script-argument: ${{ inputs.restart-vm && '--restart-vm' || '' }}
  trigger-health-check:
    name: Trigger health check
    uses: ./.github/workflows/healthcheck.yml
    needs: apply-k8s-resources
    secrets: inherit