name: Deploy Home Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'packages/**'
  workflow_call:
  workflow_dispatch:
jobs:
  start-home-server-pod:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Start home-server over SSH
        run: ssh ${{ secrets.SSH_HOST }} "bash <(curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/scripts/home-server-deploy.sh)"
  e2e-health-check:
    runs-on: ubuntu-latest
    needs: start-home-server-pod
    steps:
      - name: Health Check
        run: curl --fail ${{ secrets.HTTPS_HOST }}/health || exit 1