name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  start_home-server_pod:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy over SSH
        run: ssh -tt ${{ secrets.SERVER_HOST }} "
          ls -la
          git clone ${{ github.repositoryUrl }}
          git-crypt unlock
          ./home-server-pod-start.sh
        "
