name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  start_home-server_pod:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Start home server over SSH
        env:
          SSH_HOST: ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
          SCRIPT_URL: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/scripts/home-server-deploy.sh"
        run: ssh $SSH_HOST "bash <(curl -s ${SCRIPT_URL})"
