name: Deploy Home Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'bin/**'
      - 'packages/**'
  workflow_call:
  workflow_dispatch:
env:
  SCRIPTS_PATH: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/scripts
jobs:
  start-home-server-pod:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Start home-server over SSH
        run: ssh ${{ secrets.SSH_HOST }} "bash <(curl -s ${{ env.SCRIPTS_PATH }}/home-server-deploy.sh)"
  e2e-health-check:
    runs-on: ubuntu-latest
    needs: start-home-server-pod
    env:
      SSL_CLIENT_CERT_PATH: ${{ runner.temp }}/client.pem
      HTTPS_HOST: ${{ secrets.HTTPS_HOST }}
    steps:
      - name: Prepare SSL client certificate
        run: echo "${{ secrets.SSL_CLIENT_CERTIFICATE }}" > ${{ env.SSL_CLIENT_CERT_PATH }}
      - name: Run e2e Health Check
        run: bash ${{ env.SCRIPTS_PATH }}/home-server-health-check.sh
        