name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'packages/rust-api/**'
jobs:
  trigger-clippy:
    name: Trigger Clippy
    uses: ./.github/workflows/rust-clippy.yml
  trigger-image-ci:
    name: Trigger image CI
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      package: rust-api