name: Deploy Scaffolding
on:
  push:
    branches:
      - main
    paths:
      - .dockerignore
      - '.git-crypt/**'
      - .gitattributes
      - 'config/**'
      - packages/nginx-reverse-proxy/ssl/ca.pem
      - packages/nginx-reverse-proxy/ssl/dhparam.pem
      - 'packages/scaffolding/**'
      - 'scripts/**'
  workflow_dispatch:
concurrency:
  group: deploy-scaffolding
  cancel-in-progress: true
jobs:
  trigger-image-ci:
    name: Trigger image CI
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      package: scaffolding
      context: "."