name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'packages/rust-api/**'
jobs:
  trigger-docker-image-ci:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      package: rust-api