name: Deploy Reverse Proxy
on:
  push:
    branches:
      - main
    paths:
      - 'packages/nginx-reverse-proxy/**'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  trigger-image-ci:
    name: Trigger image CI
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      package: nginx-reverse-proxy
      add-hosts: test.home-server:127.0.0.1,test.tplinkwifi.net:127.0.0.1