name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'packages/rust-api/**'
jobs:
  trigger-home-server-deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/docker-image.yml
    with:
      package: rust-api
      image_name: rust-home-server-api
