name: Deploy Reverse Proxy
on:
  push:
    branches:
      - main
    paths:
      - 'packages/nginx-reverse-proxy/**'
jobs:
  trigger-docker-image-ci:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      package: nginx-reverse-proxy