name: Deploy Monero
on:
  push:
    branches:
      - main
    paths:
      - 'packages/monero/**'
concurrency:
  group: deploy-monero
  cancel-in-progress: true
jobs:
  trigger-image-ci:
    name: Trigger image CI
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      package: monero