name: Deploy Home Server
on:
  push:
    branches:
      - main
    paths:
      - '.git-crypt/**'
      - '.github/workflows/deploy-home-server.yml'
      - 'scripts/**'
      - '.gitattributes'
  workflow_call:
  workflow_dispatch:
    inputs:
      restart-vm:
        description: 'Restart podman virtual machine before restarting the pod'
        required: true
        default: false 
        type: boolean
concurrency:
  group: ${{ github.workflow }}
jobs:
  start-home-server-pod:
    name: Restart pod
    uses: ./.github/workflows/run-over-ssh.yml
    secrets: inherit
    with:
      deploy-script-name: home-server-deploy
      deploy-script-argument: ${{ inputs.restart-vm && '--restart-vm' || '' }}
  trigger-health-check:
    name: Trigger health check
    uses: ./.github/workflows/healthcheck.yml
    needs: start-home-server-pod
    secrets: inherit