name: Docker Image CI
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      image_name:
        required: true
        type: string
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build the Docker image
      run: docker build packages/${{ inputs.package }} --file packages/${{ inputs.package }}/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
  trigger-home-server-deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-home-server.yml
    secrets: inherit
    with:
      key: ${{ secrets.SSH_KEY }}
      known_hosts: ${{ secrets.KNOWN_HOSTS }}