name: Docker Image CI
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      context:
        required: false
        type: string
      add-hosts:
        required: false
        type: string
jobs:
  trigger-hadolint:
    name: Trigger Hadolint
    uses: ./.github/workflows/hadolint.yml
    with:
      package: ${{ inputs.package }}
  docker-build-and-push:
    name: Image build and push
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIR: packages/${{ inputs.package }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/home-server-${{ inputs.package }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set package environment variables
      run: |
        echo "TAG=$(cat ${{ env.PACKAGE_DIR }}/VERSION)" >> $GITHUB_ENV
        echo "COMMIT=$(git log -n 1 --oneline)" >> $GITHUB_ENV
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push production image
      uses: docker/build-push-action@v3
      with:
        target: production
        file: ${{ env.PACKAGE_DIR }}/Dockerfile
        context: ${{ inputs.context || env.PACKAGE_DIR }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.TAG }}
        build-args: |
          TAG=${{ env.TAG }}
          COMMIT=${{ env.COMMIT }}
          DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
          DOMAIN_EMAIL=${{ secrets.DOMAIN_EMAIL }}
        add-hosts: ${{ inputs.add-hosts }}
        cache-from: type=registry,ref=${{ env.IMAGE }}:latest-cache
        cache-to: type=registry,ref=${{ env.IMAGE }}:latest-cache,mode=max
        push: true
  trigger-snyk-container:
    name: Trigger Snyk
    needs: docker-build-and-push
    uses: ./.github/workflows/snyk-container.yml
    secrets: inherit
    with:
      package: ${{ inputs.package }}
  trigger-home-server-deploy:
    name: Trigger Home Server deploy
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-home-server.yml
    secrets: inherit