name: Docker Image CI
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
jobs:
  docker-build-and-push:
    name: Image build and push
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIR: packages/${{ inputs.package }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/home-server-${{ inputs.package }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set package environment variables
      run: |
        echo "TAG=$(cat ${{ env.PACKAGE_DIR }}/VERSION)" >> $GITHUB_ENV
        echo "COMMIT=$(git log -n 1 --oneline)" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build and push builder image
      uses: docker/build-push-action@v3
      with:
        target: builder
        context: ${{ env.PACKAGE_DIR }}
        tags: ${{ env.IMAGE }}:builder
        build-args: |
          TAG=${{ env.TAG }}
          COMMIT=${{ env.COMMIT }}
        add-hosts: |
          home-server:127.0.0.1
          tplinkwifi.net:127.0.0.1
        cache-from: type=registry,ref=${{ env.IMAGE }}:builder-cache
        cache-to: type=registry,ref=${{ env.IMAGE }}:builder-cache,mode=max
        push: true
    - name: Build and push production image
      uses: docker/build-push-action@v3
      with:
        target: production
        context: ${{ env.PACKAGE_DIR }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.TAG }}
        build-args: |
          TAG=${{ env.TAG }}
          COMMIT=${{ env.COMMIT }}
          DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
        cache-from: |
          type=registry,ref=${{ env.IMAGE }}:builder-cache
          type=registry,ref=${{ env.IMAGE }}:latest-cache
        cache-to: type=registry,ref=${{ env.IMAGE }}:latest-cache,mode=max
        push: true
  trigger-home-server-deploy:
    name: Trigger Home Server deploy
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-home-server.yml
    secrets: inherit