name: Docker Image CI
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      image_name:
        required: true
        type: string
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build packages/${{ inputs.package }} --file packages/${{ inputs.package }}/Dockerfile --tag duddu/${{ inputs.image_name }}:latest
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: duddu
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Push the Docker image
      run: docker push duddu/${{ inputs.image_name }}:latest
  trigger-home-server-deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-home-server.yml