name: Docker Image CI
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
jobs:
  docker-build-and-push:
    name: Image build and push
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/home-server-${{ inputs.package }}
      PACKAGE_DIR: packages/${{ inputs.package }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        export TAG=$(cat ${{ env.PACKAGE_DIR }}/VERSION);
        docker buildx build
          -f ${{ env.PACKAGE_DIR }}/Dockerfile
          -t ${{ env.IMAGE }}:latest
          -t ${{ env.IMAGE }}:${TAG}
          --build-arg TAG=${TAG}
          --build-arg COMMIT="$(git log -n 1 --oneline)"
          --build-arg DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            --build-arg WEBSOCKETD_VERSION=0.4.1-linux_amd64
            --add-host "home-server:127.0.0.1"
            --add-host "tplinkwifi.net:127.0.0.1"
          ${{ env.PACKAGE_DIR }}
    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push the Docker image
      run: docker push --all-tags ${{ env.IMAGE }}
  trigger-home-server-deploy:
    name: Trigger Home Server deploy
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-home-server.yml
    secrets: inherit