name: Hadolint
on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '**/Dockerfile'
permissions:
  contents: read
jobs:
  changed-dockerfiles:
    name: Detect changed Dockerfiles
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Detect changes
        uses: tj-actions/changed-files@v32.1.2
        id: changed-dockerfiles
        with:
          files: |
            **/Dockerfile
          json: true
      - name: Set dockerfiles matrix
        id: set-matrix
        run: echo "matrix={\"dockerfile\":${{ steps.changed-dockerfiles.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest
    needs:
      - changed-dockerfiles
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.changed-dockerfiles.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
          category: dockerfile