name: Hadolint
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
permissions:
  contents: read
jobs:
  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    env:
      dockerfile: packages/${{ inputs.package }}/Dockerfile
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Detect changes in Dockerfile
        uses: tj-actions/changed-files@v32.1.2
        id: changed-dockerfile
        with:
          files: ${{ env.dockerfile }}
      - name: Determine whether to continue
        if: ${{ steps.changed-dockerfile.outputs.any_changed == 'true' }}
        run: echo "do_lint=true" >> $GITHUB_ENV
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.0.0
        if: ${{ env.do_lint == 'true' }}
        with:
          dockerfile: ${{ env.dockerfile }}
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true
          verbose: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ env.do_lint == 'true' }}
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
          category: dockerfile