name: Run script over ssh
on:
  workflow_call:
    inputs:
      script-name:
        required: true
        type: string
      script-argument:
        required: true
        type: string
env:
  RAW_GITHUB_PATH: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}
jobs:
  run-on-home-server:
    name: Run script over ssh
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Run ${{ inputs.script-name }}.sh over ssh
        run:
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DOMAIN_NAME }} 
            "zsh <(curl -s ${{ env.RAW_GITHUB_PATH }}/scripts/${{ inputs.script-name }}.sh) ${{ inputs.script-argument }}"