name: Run script over ssh
on:
  workflow_call:
    inputs:
      deploy-script-name:
        required: true
        type: string
      deploy-script-argument:
        required: true
        type: string
env:
  SCRIPTS_PATH: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/scripts
jobs:
  run-on-home-server:
    name: Run script over ssh
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Run ${{ inputs.deploy-script-name }}.sh over ssh
        run:
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DOMAIN_NAME }} "
            USER=${{ secrets.SSH_USER }}
            COMMIT_SHA=${{ github.sha }}
            DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            bash <(curl -s ${{ env.SCRIPTS_PATH }}/${{ inputs.deploy-script-name }}.sh)
              ${{ inputs.deploy-script-argument }}"