name: Rust code scanning
on:
  push:
    branches:
      - main
    paths:
      - 'packages/rust-api/src/**'
      - '**.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/rust-api/src/**'
      - '**.toml'
defaults:
  run:
    shell: bash
jobs:
  rust-clippy-analyze:
    name: Run Clippy check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt
      - name: Run clippy
        run:
          cargo clippy
          --all-features
          --message-format=json
          --manifest-path packages/rust-api/Cargo.toml | 
          clippy-sarif | 
          tee rust-clippy-results.sarif | 
          sarif-fmt
        continue-on-error: true
      - name: Fix sarif artifactLocation URIs
        run: 
          sed -i 's/"src\//"packages\/rust-api\/src\//g'
          rust-clippy-results.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: rust
          sarif_file: rust-clippy-results.sarif
