name: Snyk image scan
on:
  push:
    tags:
      - '*'
jobs:
  snyk:
    name: Run vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: asdf
        run: echo $(echo '${{ github.event.ref }}' | cut -d / -f 3 | cut -d _ -f 1)
      - name: Set tag environment variables
        run: |
          PACKAGE=$(echo '${{ github.event.ref }}' | cut -d / -f 3 | cut -d _ -f 1)
          echo "PACKAGE=$PACKAGE" >> $GITHUB_ENV
          echo "TAG=$(cat packages/$PACKAGE/VERSION)" >> $GITHUB_ENV
      - name: Run Snyk vulnerability scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.repository_owner }}/home-server-${{ env.PACKAGE }}:${{ env.TAG }}
          args:
            --file=packages/${{ env.PACKAGE }}/Dockerfile
            --severity-threshold=medium
      - name: Upload scan result to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
          wait-for-processing: true
          category: image